name: Export Static Project
on:
  push:
    paths:
      - "site/**"
      - "!site/.kobweb/**"
  workflow_dispatch:
    
jobs:
  check-kobweb:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Kobweb Export Action
        uses: ./.github/export-kobweb
